In [2]:
import torch

outputs = torch.tensor([[0.1,0.2],
                        [0.05,0.4]])

#  表示从列 找最大索引
print(outputs.argmax(0))

#  表示从行  找最大索引
print(outputs.argmax(1))

preds = outputs.argmax(1)

# 真实的target
targets = torch.tensor([0,1])

#  比较预测值和真实值
print((preds == targets).sum())

tensor([0, 1])
tensor([1, 1])
tensor([False,  True])
